CREATE TABLE staging.bdc_capa_processo (
    numero_processo TEXT NOT NULL,
    tipo_procedimento TEXT,
    assunto_principal TEXT,
    tribunal TEXT,
    grau_tribunal INTEGER NOT NULL,
    tipo_tribunal TEXT,
    comarca TEXT,
    orgao_julgador TEXT,
    uf CHAR(2),
    status_processo TEXT,
    servico_ajuizamento TEXT,
    assunto_cnj TEXT,
    numero_assunto_cnj INTEGER,
    tipo_assunto_cnj TEXT,
    numero_tipo_assunto_cnj INTEGER,
    assunto_amplo_cnj TEXT,
    numero_assunto_amplo_cnj INTEGER,
    qtde_volumes INTEGER,
    qtde_paginas INTEGER,
    valor_causa NUMERIC(15,2),
    data_coisa_julgada DATE,
    data_encerramento DATE,
    data_distribuicao DATE,
    data_publicacao DATE,
    data_aviso DATE,
    data_ultimo_movimento DATE,
    data_captura TIMESTAMP,
    data_ultima_atualizacao TIMESTAMP,
    idade_processo INTEGER,
    media_atualizacoes_mensal NUMERIC(10,2),
    motivo_dado_oculto TEXT,
    data_insercao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    parte_ativa TEXT,
    parte_passiva TEXT,
    CONSTRAINT bdc_capa_processo_unique UNIQUE (numero_processo, grau_tribunal)
);
